# This is a basic workflow to update the submodule in the strudel repo when necessary

name: strudel-sync

# Controls when the action will run. Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.1.0
      with:
        # Repository name with owner. For example, actions/checkout
        # Default: ${{ github.repository }}
        repository: 'https://github.com/umrlastig/strudel.git'
        # Whether to checkout submodules: `true` to checkout submodules or `recursive` to
        # recursively checkout submodules.
        #
        # When the `ssh-key` input is not provided, SSH URLs beginning with
        # `git@github.com:` are converted to HTTPS.
        #
        # Default: false
        submodules: 'recursive'
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Updating remote data files from lastig_data" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.SYNC_WITH_STRUDEL_TOKEN }}
        branch: gh_pages
        repository: 'https://github.com/umrlastig/strudel.git'
